version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  
services:
  router-satellite-alpine:
    build:
      context: .
      args:
        CONTAINER_INTERNAL_SSH_PORT: ${CONTAINER_INTERNAL_SSH_PORT}
        CONTAINER_SSH_FILE_NAME: ${CONTAINER_SSH_FILE_NAME}
        ROUTER_SSH_IP: ${ROUTER_SSH_IP}
        ROUTER_SSH_PORT: ${ROUTER_SSH_PORT}
        ROUTER_SSH_FILE_NAME: ${ROUTER_SSH_FILE_NAME}
        ROUTER_SSH_USERNAME: ${ROUTER_SSH_USERNAME}
    env_file: "./Private/.env"
    environment:
      CONTAINER_INTERNAL_SSH_PORT: ${CONTAINER_INTERNAL_SSH_PORT}
      CONTAINER_SSH_FILE_NAME: ${CONTAINER_SSH_FILE_NAME}
      ROUTER_SSH_IP: ${ROUTER_SSH_IP}
      ROUTER_SSH_PORT: ${ROUTER_SSH_PORT}
      ROUTER_SSH_FILE_NAME: ${ROUTER_SSH_FILE_NAME}
      ROUTER_SSH_USERNAME: ${ROUTER_SSH_USERNAME}
    ports:
      - "${CONTAINER_INTERNAL_SSH_PORT}:${CONTAINER_INTERNAL_SSH_PORT}"
      # - ${CONTAINER_EXTERNAL_SSH_PORT}:${CONTAINER_INTERNAL_SSH_PORT}