version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}

services:

  router-satellite-ubuntu:
    image: router-satellite-ubuntu:latest
    container_name: router-satellite-ubuntu
    restart: always
    volumes:
      # - "./router-satellite-swift:/router-satellite-swift"
      - "./data:/data"
    build:
      context: .
    environment:
      <<: *shared_environment
      PASSWD: ${ALPINE_ROOT_PASSWORD}
    ports:
      - ${ALPINE_SSH_EXTERNAL_PORT}:${ALPINE_SSH_INTERNAL_PORT}
