version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}

services:

  router-satellite-alpine:
    image: router-satellite-alpine:latest
    container_name: router-satellite-alpine
    restart: always
    build:
      context: .
    environment:
      <<: *shared_environment
      SSH_INTERNAL_PORT: ${SSH_INTERNAL_PORT}
    ports:
      - ${SSH_EXTERNAL_PORT}:${SSH_INTERNAL_PORT}
