version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}

services:

  router-satellite-ubuntu:
    image: router-satellite-ubuntu:latest
    container_name: router-satellite-ubuntu
    restart: always
    build:
      context: .
    environment:
      <<: *shared_environment
      PASSWD: ${ALPINE_ROOT_PASSWORD}
    ports:
      - ${UBUNTU_SSH_EXTERNAL_PORT}:${UBUNTU_SSH_INTERNAL_PORT}
