version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  
services:
  router-satellite-alpine:
    build:
      context: .
    env_file: "./Private/.env"
    environment:
      CONTAINER_INTERNAL_SSH_PORT: ${CONTAINER_INTERNAL_SSH_PORT}
      ROUTER_IP: ${ROUTER_IP}
      ROUTER_SSH_PORT: ${ROUTER_SSH_PORT}
      SSH_FILE_NAME: ${SSH_FILE_NAME}
    ports:
      - ${CONTAINER_EXTERNAL_SSH_PORT}:${CONTAINER_INTERNAL_SSH_PORT}